name: Gradle Assemble and Test
on:
  pull_request:
jobs:
  gradle:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Gradle assemble
      run: ./gradlew assemble

    - name: Gradle test
      run: ./gradlew iosX64Test
